# Generated by Django 3.0.3 on 2025-10-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название корпуса')),
                ('description', models.TextField(verbose_name='Описание корпуса')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('scientific', 'Научная литература'), ('news', 'Новости'), ('academic', 'Академические тексты'), ('technical', 'Техническая документация')], max_length=20, verbose_name='Жанр корпуса')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название текста')),
                ('description', models.TextField(verbose_name='Описание текста')),
                ('content', models.TextField(verbose_name='Текст')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='db.Corpus', verbose_name='Корпус')),
                ('has_translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='db.Text', verbose_name='Перевод текста')),
            ],
        ),
    ]
