# Generated by Django 3.0.3 on 2025-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_corpus_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='text',
            name='embeddings',
            field=models.TextField(default={}, verbose_name='Ембеддинг текста'),
            preserve_default=False,
        ),
    ]
